//! Raw FFI bindings to PJSIP via the pjsua high-level C API.
//!
//! This crate is auto-generated by bindgen. Do not edit the bindings directly.
//! All PJSIP calls are unsafe — use the `pale-core` crate for a safe wrapper.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pjsua_lifecycle() {
        unsafe {
            // Create PJSUA instance
            // PJ_SUCCESS is 0 (defined as a C macro, not exported by bindgen)
            let status = pjsua_create();
            assert_eq!(status, 0, "pjsua_create failed");

            // Destroy (we skip init/start since we just want to verify linking works)
            pjsua_destroy();
        }
    }
}
