use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Pinned PJSIP version
const PJSIP_VERSION: &str = "2.14.1";
const PJSIP_TARBALL: &str = "pjproject-2.14.1.tar.gz";
const PJSIP_URL: &str = "https://github.com/pjsip/pjproject/archive/refs/tags/2.14.1.tar.gz";
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=wrapper.h");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let pj_src_dir = out_dir.join(format!("pjproject-{}", PJSIP_VERSION));

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();

    // Step 1: Download PJSIP source if not present
    if !pj_src_dir.exists() {
        download_pjsip(&out_dir);
    }

    // Step 2: Build PJSIP if not already built
    // Check for the existence of the core libpj to avoid expensive rebuilds
    let pj_lib_dir = pj_src_dir.join("pjlib/lib");
    let already_built = pj_lib_dir.exists()
        && fs::read_dir(&pj_lib_dir)
            .map(|entries| entries.count() > 0)
            .unwrap_or(false);

    if !already_built {
        write_config_site(&pj_src_dir, &target_os);
        build_pjsip(&pj_src_dir, &target_os, &target_arch);
    } else {
        println!("cargo:warning=PJSIP already built, skipping compilation.");
    }

    // MSVC names libs with versioned suffixes; normalize them (also for
    // cache-restored trees, where the build step is skipped) before linking.
    let is_msvc = env::var("TARGET").unwrap_or_default().contains("msvc");
    if target_os == "windows" && is_msvc {
        normalize_msvc_libs(&pj_src_dir);
    }

    // Step 3: Emit linker directives
    emit_link_directives(&pj_src_dir, &target_os, &target_arch);

    // Step 4: Generate Rust bindings via bindgen
    generate_bindings(&pj_src_dir, &out_dir, &target_os);
}

/// Download and extract PJSIP source tarball
fn download_pjsip(out_dir: &Path) {
    let tarball_path = out_dir.join(PJSIP_TARBALL);

    if !tarball_path.exists() {
        println!("cargo:warning=Downloading PJSIP {}...", PJSIP_VERSION);
        let status = Command::new("curl")
            .args(["-L", "-o", tarball_path.to_str().unwrap(), PJSIP_URL])
            .status()
            .expect("Failed to run curl. Is curl installed?");
        assert!(status.success(), "Failed to download PJSIP tarball");
    }

    println!("cargo:warning=Extracting PJSIP...");
    let status = Command::new("tar")
        .args(["xzf", tarball_path.to_str().unwrap()])
        .current_dir(out_dir)
        .status()
        .expect("Failed to run tar");
    assert!(status.success(), "Failed to extract PJSIP tarball");
}

/// Write config_site.h with platform-appropriate defines
fn write_config_site(pj_src_dir: &Path, target_os: &str) {
    let config_path = pj_src_dir.join("pjlib/include/pj/config_site.h");
    let mut config = String::new();

    config.push_str("/* Auto-generated by pjsip-sys build.rs */\n");
    config.push_str("#define PJ_HAS_IPV6 1\n");
    config.push_str("#define PJMEDIA_HAS_SRTP 1\n");
    config.push_str("#define PJMEDIA_HAS_VIDEO 1\n");
    config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_NULL 1\n");
    config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 0\n");
    if target_os != "windows" {
        config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_WMME 0\n");
    }

    match target_os {
        "macos" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_DARWIN 1\n");
        }
        "linux" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_ALSA 1\n");
        }
        "windows" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_WMME 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_DSHOW 0\n");
            if let Some(vcpkg) = vcpkg_installed_dir() {
                if vcpkg_has_lib(&vcpkg, "libssl") && vcpkg_has_lib(&vcpkg, "libcrypto") {
                    config.push_str("#define PJ_HAS_SSL_SOCK 1\n");
                }
                if vcpkg_has_lib(&vcpkg, "opus") {
                    config.push_str("#define PJMEDIA_HAS_OPUS_CODEC 1\n");
                }
            }
        }
        "android" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1\n");
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_ANDROID 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_ANDROID 1\n");
            config.push_str("#define PJ_ANDROID 1\n");
        }
        "ios" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_IOS 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_DARWIN 1\n");
        }
        _ => {}
    }

    fs::write(&config_path, config)
        .unwrap_or_else(|e| panic!("Failed to write config_site.h: {}", e));
}

/// Simplify an MSVC lib name produced by the pjproject solution build.
/// msbuild names libs `<project>-<cpu>-<platform>-vc<ver>-<config>.lib`
/// (e.g. "pjsua_lib-x86_64-x64-vc14-Release.lib" → "pjsua.lib").
/// Project names come from pjproject-vs14.sln and use underscores.
fn simplify_msvc_lib_name(name: &str) -> String {
    let stem = name.strip_suffix(".lib").unwrap_or(name);
    // Longest/most-specific prefixes first — "pjlib" would otherwise match
    // "pjlib-util". The projects override TargetName with hyphenated stems
    // (pjsua-lib-x86_64-x64-vc14-Release.lib); underscore variants are kept
    // as a fallback in case a project uses its raw name.
    let mappings = [
        ("pjsua2-lib", "pjsua2"),
        ("pjsua2_lib", "pjsua2"),
        ("pjsua-lib", "pjsua"),
        ("pjsua_lib", "pjsua"),
        ("pjsip-ua", "pjsip-ua"),
        ("pjsip_ua", "pjsip-ua"),
        ("pjsip-simple", "pjsip-simple"),
        ("pjsip_simple", "pjsip-simple"),
        ("pjsip-core", "pjsip"),
        ("pjsip_core", "pjsip"),
        ("pjmedia-codec", "pjmedia-codec"),
        ("pjmedia_codec", "pjmedia-codec"),
        ("pjmedia-audiodev", "pjmedia-audiodev"),
        ("pjmedia_audiodev", "pjmedia-audiodev"),
        ("pjmedia-videodev", "pjmedia-videodev"),
        ("pjmedia_videodev", "pjmedia-videodev"),
        ("pjmedia", "pjmedia"),
        ("pjnath", "pjnath"),
        ("pjlib-util", "pjlib-util"),
        ("pjlib_util", "pjlib-util"),
        ("pjlib", "pj"),
        ("libsrtp", "srtp"),
        ("libresample", "resample"),
        ("libg7221codec", "g7221codec"),
        ("libilbccodec", "ilbccodec"),
        ("libspeex", "speex"),
        ("libgsmcodec", "gsmcodec"),
        ("libmilenage", "milenage"),
        ("libbaseclasses", "baseclasses"),
        ("libwebrtc", "webrtc"),
        ("libyuv", "yuv"),
    ];
    for (prefix, lib_name) in &mappings {
        if stem.starts_with(prefix) {
            return format!("{}.lib", lib_name);
        }
    }
    String::new()
}

/// Directories where the pjproject msbuild solution drops .lib files.
/// OutDir is `..\lib\` relative to each .vcxproj; third_party projects live
/// one level deeper (third_party/build/<name>/), so their libs land in
/// third_party/build/lib.
fn msvc_lib_dirs(pj_src_dir: &Path) -> Vec<PathBuf> {
    [
        "pjlib/lib",
        "pjlib-util/lib",
        "pjnath/lib",
        "pjmedia/lib",
        "pjsip/lib",
        "third_party/lib",
        "third_party/build/lib",
    ]
    .iter()
    .map(|sub| pj_src_dir.join(sub))
    .filter(|p| p.exists())
    .collect()
}

/// Copy versioned MSVC libs to the plain names the link directives use.
fn normalize_msvc_libs(pj_src_dir: &Path) {
    for dir in msvc_lib_dirs(pj_src_dir) {
        let Ok(entries) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.extension().map_or(false, |e| e == "lib") {
                continue;
            }
            let fname = path.file_name().unwrap().to_string_lossy().to_string();
            let simple = simplify_msvc_lib_name(&fname);
            if !simple.is_empty() && simple != fname {
                let dest = dir.join(&simple);
                if !dest.exists() {
                    fs::copy(&path, &dest).ok();
                }
                println!("cargo:warning=MSVC lib: {} -> {}", fname, simple);
            }
        }
    }
}

/// Locate the vcpkg installed-triplet dir (for OpenSSL/Opus on Windows MSVC).
fn vcpkg_installed_dir() -> Option<PathBuf> {
    let triplet =
        env::var("PALE_VCPKG_TRIPLET").unwrap_or_else(|_| "x64-windows-static-md".to_string());
    let root = env::var("VCPKG_ROOT")
        .or_else(|_| env::var("VCPKG_INSTALLATION_ROOT"))
        .ok()?;
    let dir = Path::new(&root).join("installed").join(triplet);
    dir.exists().then_some(dir)
}

fn vcpkg_has_lib(installed: &Path, lib: &str) -> bool {
    installed.join("lib").join(format!("{}.lib", lib)).exists()
}

/// Find msbuild.exe on Windows (VS 2019/2022)
fn find_msbuild() -> Option<String> {
    // Try vswhere first
    let vswhere =
        Command::new("C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe")
            .args([
                "-latest",
                "-requires",
                "Microsoft.Component.MSBuild",
                "-find",
                "MSBuild\\**\\Bin\\MSBuild.exe",
            ])
            .output()
            .ok()?;
    let path = String::from_utf8_lossy(&vswhere.stdout).trim().to_string();
    if !path.is_empty() {
        return Some(path);
    }
    // Fallback: check PATH
    if Command::new("msbuild").arg("/version").output().is_ok() {
        return Some("msbuild".to_string());
    }
    None
}

fn build_pjsip(pj_src_dir: &Path, target_os: &str, target_arch: &str) {
    println!(
        "cargo:warning=Building PJSIP {} for {}/{}...",
        PJSIP_VERSION, target_os, target_arch
    );

    // Determine OpenSSL path
    let openssl_prefix = find_openssl_prefix(target_os);

    // Build configure arguments.
    // Pin auto-detected optional video deps to what we actually want.
    // VP8 (libvpx) is enabled for video calls; FFmpeg/SDL are disabled.
    let mut configure_args = vec![
        "./configure".to_string(),
        "--enable-shared=no".to_string(),
        "--disable-ffmpeg".to_string(),
        "--disable-openh264".to_string(),
        "--disable-sdl".to_string(),
    ];

    // Enable VP8 where libvpx is available (native desktop builds).
    // Disable on mobile and when cross-compiling (pkg-config gives wrong arch libs).
    let is_cross = target_os == "android"
        || target_os == "ios"
        || (target_os == "macos" && target_arch != std::env::consts::ARCH);
    if is_cross {
        configure_args.push("--disable-vpx".to_string());
    }

    // Windows cross/native compilation
    let is_windows_cross = target_os == "windows" && cfg!(target_os = "linux");
    let is_windows_msvc =
        target_os == "windows" && env::var("TARGET").unwrap_or_default().contains("msvc");
    if target_os == "windows" && !is_windows_msvc {
        // GNU target: use MinGW
        configure_args.push("--host=x86_64-w64-mingw32".to_string());
        if is_windows_cross {
            configure_args.push("--build=x86_64-pc-linux-gnu".to_string());
        } else {
            configure_args.push("--build=x86_64-w64-mingw32".to_string());
        }
    }

    // Android cross-compilation
    if target_os == "android" {
        let ndk_home = env::var("NDK_HOME")
            .or_else(|_| env::var("ANDROID_NDK_HOME"))
            .or_else(|_| env::var("ANDROID_NDK_ROOT"))
            .unwrap_or_else(|_| {
                let android_home = env::var("ANDROID_HOME")
                    .expect("NDK_HOME or ANDROID_HOME must be set for Android builds");
                let ndk_dir = Path::new(&android_home).join("ndk");
                if let Ok(entries) = fs::read_dir(&ndk_dir) {
                    let mut versions: Vec<String> = entries
                        .filter_map(|e| e.ok())
                        .filter_map(|e| e.file_name().into_string().ok())
                        .collect();
                    versions.sort();
                    if let Some(latest) = versions.last() {
                        return ndk_dir.join(latest).to_string_lossy().to_string();
                    }
                }
                panic!("No NDK found in {}", ndk_dir.display());
            });

        let host_tag = if cfg!(target_os = "macos") {
            "darwin-x86_64"
        } else if cfg!(target_os = "linux") {
            "linux-x86_64"
        } else {
            "windows-x86_64"
        };

        let toolchain = format!("{}/toolchains/llvm/prebuilt/{}", ndk_home, host_tag);
        let sysroot = format!("{}/sysroot", toolchain);
        let api_level = "24";

        let android_target = match target_arch {
            "aarch64" => "aarch64-linux-android",
            "arm" => "armv7a-linux-androideabi",
            "x86_64" => "x86_64-linux-android",
            "x86" => "i686-linux-android",
            _ => panic!("Unsupported Android arch: {}", target_arch),
        };

        let cc = format!("{}/bin/{}{}-clang", toolchain, android_target, api_level);
        let cxx = format!("{}/bin/{}{}-clang++", toolchain, android_target, api_level);
        configure_args.push(format!("--host={}", android_target));
        configure_args.push(format!("CC={}", cc));
        configure_args.push(format!("CXX={}", cxx));
        configure_args.push(format!("CPP={} -E", cc));
        configure_args.push(format!("AR={}/bin/llvm-ar", toolchain));
        configure_args.push(format!("RANLIB={}/bin/llvm-ranlib", toolchain));
        configure_args.push(format!("STRIP={}/bin/llvm-strip", toolchain));
        configure_args.push(format!("LD={}/bin/ld.lld", toolchain));

        // Store toolchain info for make env
        env::set_var("PALE_ANDROID_CC", &cc);
        env::set_var("PALE_ANDROID_SYSROOT", &sysroot);
        env::set_var("PALE_ANDROID_TOOLCHAIN", &toolchain);
    }

    // iOS cross-compilation
    if target_os == "ios" {
        let ios_target = match target_arch {
            "aarch64" => "arm64-apple-ios",
            "x86_64" => "x86_64-apple-ios-simulator",
            _ => panic!("Unsupported iOS arch: {}", target_arch),
        };

        let sdk = if target_arch == "x86_64" {
            "iphonesimulator"
        } else {
            "iphoneos"
        };
        let sdk_path_output = Command::new("xcrun")
            .args(["--sdk", sdk, "--show-sdk-path"])
            .output()
            .expect("Failed to find iOS SDK path");
        let sdk_path = String::from_utf8_lossy(&sdk_path_output.stdout)
            .trim()
            .to_string();

        let min_ios = "15.0";
        configure_args.push(format!("--host={}", ios_target));
        configure_args.push(format!(
            "CFLAGS=-isysroot {} -miphoneos-version-min={} -arch {} -fembed-bitcode",
            sdk_path,
            min_ios,
            if target_arch == "aarch64" {
                "arm64"
            } else {
                "x86_64"
            }
        ));
    }

    if target_os == "windows" && is_windows_cross {
        // Cross-compiling from Linux: use custom-built OpenSSL/Opus
        let home = env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        let ssl_dir = env::var("OPENSSL_DIR").unwrap_or_else(|_| format!("{}/openssl-win64", home));
        let opus_dir = env::var("OPUS_DIR").unwrap_or_else(|_| format!("{}/opus-win64", home));
        if Path::new(&ssl_dir).exists() {
            configure_args.push(format!("--with-ssl={}", ssl_dir));
        }
        if Path::new(&opus_dir).exists() {
            configure_args.push(format!("--with-opus={}", opus_dir));
        }
    } else if target_os == "windows" {
        // Native Windows (MSYS2)
        let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
        let msys2_unix = msys2.replace('\\', "/").replace("C:", "/c");
        configure_args.push(format!("--with-ssl={}/mingw64", msys2_unix));
        configure_args.push(format!("--with-opus={}/mingw64", msys2_unix));
    } else if target_os == "android" {
        // Android: disable OpenSSL and Opus in PJSIP to avoid host /usr/include contamination.
        // TLS is handled by the Rust layer (reqwest + rustls), not PJSIP.
        configure_args.push("--disable-ssl".to_string());
        configure_args.push("--disable-opus".to_string());
    } else {
        if let Some(ref ssl_prefix) = openssl_prefix {
            configure_args.push(format!("--with-ssl={}", ssl_prefix));
        }
        if let Some(opus_prefix) = find_opus_prefix(target_os) {
            configure_args.push(format!("--with-opus={}", opus_prefix));
        }
    }

    // Set CFLAGS
    let android_sysroot = env::var("PALE_ANDROID_SYSROOT").unwrap_or_default();
    // Collect extra include/lib paths from pkg-config so configure can find
    // optional deps like libvpx on macOS (Homebrew) and Linux.
    let mut extra_cflags = String::new();
    let mut extra_ldflags = String::new();
    if !is_cross {
        for dep in &["vpx"] {
            if let Ok(out) = Command::new("pkg-config").args(["--cflags", dep]).output() {
                if out.status.success() {
                    extra_cflags.push(' ');
                    extra_cflags.push_str(String::from_utf8_lossy(&out.stdout).trim());
                }
            }
            if let Ok(out) = Command::new("pkg-config").args(["--libs", dep]).output() {
                if out.status.success() {
                    extra_ldflags.push(' ');
                    extra_ldflags.push_str(String::from_utf8_lossy(&out.stdout).trim());
                }
            }
        }
    }

    // macOS cross-compilation: when building x86_64 on ARM (or vice versa),
    // pass --host and -arch to configure so PJSIP builds for the right arch.
    let macos_cross = target_os == "macos" && target_arch != std::env::consts::ARCH;
    if macos_cross {
        let host_triple = match target_arch {
            "x86_64" => "x86_64-apple-darwin",
            "aarch64" => "arm-apple-darwin",
            _ => "x86_64-apple-darwin",
        };
        configure_args.push(format!("--host={}", host_triple));
    }

    let cflags = format!(
        "-O2 -fPIC -DPJMEDIA_HAS_SRTP=1 -DPJ_HAS_IPV6=1 {}{}",
        match target_os {
            "macos" if macos_cross => format!(
                "-mmacosx-version-min=11.0 -arch {}",
                if target_arch == "aarch64" { "arm64" } else { target_arch }
            ),
            "macos" => "-mmacosx-version-min=11.0".to_string(),
            "android" => format!("-DPJ_ANDROID=1 --sysroot={}", android_sysroot),
            _ => String::new(),
        },
        extra_cflags,
    );

    // For Android, write a wrapper script that sets CC with --sysroot
    // This avoids shell quoting issues when passing CC with spaces to configure
    if target_os == "android" && !android_sysroot.is_empty() {
        let wrapper_dir = pj_src_dir.parent().unwrap_or(pj_src_dir);
        // Create CC wrapper script
        let cc_wrapper = wrapper_dir.join("ndk-cc.sh");
        let cc_path = env::var("PALE_ANDROID_CC").unwrap_or_default();
        fs::write(
            &cc_wrapper,
            format!(
                "#!/bin/sh\nexec {} --sysroot={} \"$@\"\n",
                cc_path, android_sysroot
            ),
        )
        .ok();
        let _ = Command::new("chmod").arg("+x").arg(&cc_wrapper).status();
        // Replace CC/CXX/CPP in configure args with wrapper
        let cc_w = cc_wrapper.to_string_lossy().to_string();
        configure_args
            .retain(|a| !a.starts_with("CC=") && !a.starts_with("CXX=") && !a.starts_with("CPP="));
        configure_args.push(format!("CC={}", cc_w));
        let cxx_wrapper = wrapper_dir.join("ndk-cxx.sh");
        let cxx_path = cc_path.replace("clang", "clang++");
        fs::write(
            &cxx_wrapper,
            format!(
                "#!/bin/sh\nexec {} --sysroot={} \"$@\"\n",
                cxx_path, android_sysroot
            ),
        )
        .ok();
        let _ = Command::new("chmod").arg("+x").arg(&cxx_wrapper).status();
        configure_args.push(format!("CXX={}", cxx_wrapper.to_string_lossy()));
        let cpp_wrapper = wrapper_dir.join("ndk-cpp.sh");
        fs::write(
            &cpp_wrapper,
            format!(
                "#!/bin/sh\nexec {} -E --sysroot={} \"$@\"\n",
                cc_path, android_sysroot
            ),
        )
        .ok();
        let _ = Command::new("chmod").arg("+x").arg(&cpp_wrapper).status();
        configure_args.push(format!("CPP={}", cpp_wrapper.to_string_lossy()));
    }

    // Determine shell and make commands
    // On Windows, use MSYS2 bash/make (pre-installed on GitHub Actions runners)
    let (sh_cmd, make_cmd) = if target_os == "windows" && !is_windows_cross {
        // Native Windows: use MSYS2 bash/make
        let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
        let sh = format!("{}/usr/bin/bash.exe", msys2);
        let mk = format!("{}/usr/bin/make.exe", msys2);
        (sh, mk)
    } else {
        // Linux (including cross-compile to Windows)
        ("sh".to_string(), "make".to_string())
    };

    // MSVC Windows: use msbuild with Visual Studio solution instead of autotools
    if is_windows_msvc {
        // Find msbuild and solution file
        let msbuild = find_msbuild().unwrap_or_else(|| "msbuild".to_string());
        let sln = [
            "pjproject-vs16.sln",
            "pjproject-vs14.sln",
            "pjproject-vs17.sln",
        ]
        .iter()
        .map(|name| pj_src_dir.join(name))
        .find(|p| p.exists())
        .unwrap_or_else(|| {
            panic!(
                "No Visual Studio solution file found in {}",
                pj_src_dir.display()
            );
        });
        println!(
            "cargo:warning=Using solution: {}",
            sln.file_name().unwrap().to_string_lossy()
        );

        // Build only the static libraries we link against. The solution's
        // test/sample/app executables are skipped: they are not needed and
        // their nmake link steps cannot see the vcpkg OpenSSL libs.
        let lib_targets = [
            "pjlib",
            "pjlib_util",
            "pjnath",
            "pjmedia",
            "pjmedia_audiodev",
            "pjmedia_codec",
            "pjmedia_videodev",
            "pjsip_core",
            "pjsip_simple",
            "pjsip_ua",
            "pjsua_lib",
            "libbaseclasses",
            "libg7221codec",
            "libgsmcodec",
            "libilbccodec",
            "libmilenage",
            "libresample",
            "libspeex",
            "libsrtp",
            "libwebrtc",
            "libyuv",
        ];
        let mut msbuild_cmd = Command::new(&msbuild);
        msbuild_cmd
            .arg(sln.to_str().unwrap())
            .arg(format!("/t:{}", lib_targets.join(";")))
            .args([
                "/p:Configuration=Release",
                "/p:Platform=x64",
                "/p:PlatformToolset=v143",
                "/p:WindowsTargetPlatformVersion=10.0",
                "/m",
                "/verbosity:minimal",
            ])
            .current_dir(pj_src_dir);

        // Make vcpkg OpenSSL/Opus headers visible to every cl.exe invocation.
        // (cl.exe prepends options from the CL env var; msbuild passes it through.)
        if let Some(vcpkg) = vcpkg_installed_dir() {
            let mut cl = env::var("CL").unwrap_or_default();
            if !cl.is_empty() {
                cl.push(' ');
            }
            cl.push_str(&format!("/I\"{}\"", vcpkg.join("include").display()));
            msbuild_cmd.env("CL", &cl);
            println!(
                "cargo:warning=Using vcpkg headers from {}",
                vcpkg.join("include").display()
            );
        } else {
            println!("cargo:warning=vcpkg not found: building PJSIP without OpenSSL (no SIP TLS) and without Opus");
        }

        let status = msbuild_cmd
            .status()
            .expect("Failed to run msbuild for PJSIP");
        assert!(status.success(), "PJSIP msbuild failed");

        println!("cargo:warning=PJSIP build complete (MSVC).");
        return;
    }

    // Run configure (autotools path for non-MSVC)
    let mut configure_cmd = Command::new(&sh_cmd);
    // Ensure pkg-config can find Homebrew/system libraries (e.g. libvpx, opus)
    let pkg_config_path = env::var("PKG_CONFIG_PATH").unwrap_or_default();
    let extra_pkg_paths = if target_os == "macos" {
        "/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig"
    } else {
        ""
    };
    let full_pkg_config_path = if pkg_config_path.is_empty() {
        extra_pkg_paths.to_string()
    } else {
        format!("{extra_pkg_paths}:{pkg_config_path}")
    };

    configure_cmd
        .arg("-c")
        .arg(&configure_args.join(" "))
        .env("CFLAGS", &cflags)
        .env("LDFLAGS", if macos_cross {
            format!("-arch {} {}", if target_arch == "aarch64" { "arm64" } else { target_arch }, extra_ldflags)
        } else {
            extra_ldflags.clone()
        })
        .env("PKG_CONFIG_PATH", &full_pkg_config_path)
        .current_dir(pj_src_dir);

    // For Android, ensure NDK toolchain is on PATH so configure finds the compiler
    if target_os == "android" {
        if let Ok(toolchain) = env::var("PALE_ANDROID_TOOLCHAIN") {
            let path = format!("{}/bin:{}", toolchain, env::var("PATH").unwrap_or_default());
            configure_cmd.env("PATH", &path);
        }
    }

    let status = configure_cmd
        .status()
        .expect("Failed to run PJSIP configure");
    assert!(status.success(), "PJSIP configure failed");

    let num_jobs = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    // Build make commands with proper environment
    let wrapper_dir = pj_src_dir.parent().unwrap_or(pj_src_dir).to_path_buf();
    let setup_make_env = |cmd: &mut Command| {
        if target_os == "android" {
            if let Ok(toolchain) = env::var("PALE_ANDROID_TOOLCHAIN") {
                let path = format!("{}/bin:{}", toolchain, env::var("PATH").unwrap_or_default());
                cmd.env("PATH", &path);
                // Use the wrapper scripts that embed --sysroot
                let cc_w = wrapper_dir.join("ndk-cc.sh");
                let cxx_w = wrapper_dir.join("ndk-cxx.sh");
                if cc_w.exists() {
                    cmd.env("CC", cc_w.to_string_lossy().as_ref());
                    cmd.env("CXX", cxx_w.to_string_lossy().as_ref());
                }
            }
        }
    };

    // Run make dep
    let mut dep_cmd = Command::new(&make_cmd);
    dep_cmd
        .args(["dep", &format!("-j{}", num_jobs)])
        .current_dir(pj_src_dir);
    setup_make_env(&mut dep_cmd);
    let status = dep_cmd.status().expect("Failed to run make dep");
    assert!(status.success(), "PJSIP make dep failed");

    // Run make. PJSIP's makefiles have a dependency race under -jN that
    // intermittently fails mid-build; a serial retry from where it stopped
    // always converges.
    let mut build_cmd = Command::new(&make_cmd);
    build_cmd
        .arg(&format!("-j{}", num_jobs))
        .current_dir(pj_src_dir);
    setup_make_env(&mut build_cmd);
    let status = build_cmd.status().expect("Failed to run make");
    if !status.success() {
        println!("cargo:warning=PJSIP parallel make failed; retrying serially...");
        let mut retry_cmd = Command::new(&make_cmd);
        retry_cmd.current_dir(pj_src_dir);
        setup_make_env(&mut retry_cmd);
        let status = retry_cmd
            .status()
            .expect("Failed to run make (serial retry)");
        assert!(status.success(), "PJSIP make failed");
    }

    println!("cargo:warning=PJSIP build complete.");
}

/// Emit cargo:rustc-link-lib and cargo:rustc-link-search directives
fn emit_link_directives(pj_src_dir: &Path, target_os: &str, target_arch: &str) {
    let is_msvc = env::var("TARGET").unwrap_or_default().contains("msvc");

    // MSVC path: look for .lib files directly (normalized from the msbuild output)
    if is_msvc && target_os == "windows" {
        let lib_dirs = msvc_lib_dirs(pj_src_dir);
        for dir in &lib_dirs {
            println!("cargo:rustc-link-search=native={}", dir.display());
        }
        // Link PJSIP libs by their simplified names
        let pjsip_libs = [
            "pjsua",
            "pjsip-ua",
            "pjsip-simple",
            "pjsip",
            "pjmedia-codec",
            "pjmedia",
            "pjmedia-audiodev",
            "pjmedia-videodev",
            "pjnath",
            "pjlib-util",
            "pj",
            "srtp",
            "resample",
            "g7221codec",
            "ilbccodec",
            "speex",
            "gsmcodec",
            "milenage",
            "baseclasses",
            "webrtc",
            "yuv",
        ];
        for lib in &pjsip_libs {
            let found = lib_dirs
                .iter()
                .any(|dir| dir.join(format!("{}.lib", lib)).exists());
            if found {
                println!("cargo:rustc-link-lib=static={}", lib);
            } else {
                println!("cargo:warning=PJSIP lib not found, skipping: {}", lib);
            }
        }
        // Platform libs handled below, so don't return here
    }

    // Skip the .a suffix detection path for MSVC
    if is_msvc && target_os == "windows" {
        // Already handled above, skip to platform libs
    } else {
        let lib_dirs = find_pjsip_lib_dirs(pj_src_dir);

        // PJSIP names its static libs with the host triple suffix, e.g.:
        //   libpj-arm-apple-darwin24.6.0.a
        //   libpjsip-ua-arm-apple-darwin24.6.0.a
        // Cargo's `rustc-link-lib=static=pj` looks for `libpj.a`.
        // Detect the suffix from libpj-*.a (which is unambiguous) then strip it from all libs.
        let platform_suffix = detect_platform_suffix(&lib_dirs);
        if let Some(ref suffix) = platform_suffix {
            println!("cargo:warning=Detected PJSIP platform suffix: -{}", suffix);
            for dir in &lib_dirs {
                if let Ok(entries) = fs::read_dir(dir) {
                    for entry in entries.flatten() {
                        let name = entry.file_name().to_string_lossy().to_string();
                        let suffixed = format!("-{}.a", suffix);
                        if name.starts_with("lib") && name.ends_with(&suffixed) {
                            let base = &name[..name.len() - suffixed.len()];
                            let unsuffixed = format!("{}.a", base);
                            let dest = dir.join(&unsuffixed);
                            if !dest.exists() {
                                let _ = fs::copy(entry.path(), &dest);
                            }
                        }
                    }
                }
            }
        }

        for dir in &lib_dirs {
            println!("cargo:rustc-link-search=native={}", dir.display());
        }

        // Link PJSIP static libraries — ORDER MATTERS (highest-level first)
        let pjsip_libs = [
            "pjsua",
            "pjsip-ua",
            "pjsip-simple",
            "pjsip",
            "pjmedia-codec",
            "pjmedia",
            "pjmedia-audiodev",
            "pjmedia-videodev",
            "pjsdp",
            "pjnath",
            "pjlib-util",
            "pj",
            "srtp",
            "resample",
            "g7221codec",
            "ilbccodec",
            "speex",
            "gsmcodec",
            "webrtc",
            "yuv",
        ];

        for lib in &pjsip_libs {
            let found = lib_dirs
                .iter()
                .any(|dir| dir.join(format!("lib{}.a", lib)).exists());
            if found {
                println!("cargo:rustc-link-lib=static={}", lib);
            }
        }
    } // close else block for non-MSVC path

    // Platform system libraries
    match target_os {
        "macos" => {
            println!("cargo:rustc-link-lib=framework=AudioToolbox");
            println!("cargo:rustc-link-lib=framework=AudioUnit");
            println!("cargo:rustc-link-lib=framework=CoreAudio");
            println!("cargo:rustc-link-lib=framework=CoreFoundation");
            println!("cargo:rustc-link-lib=framework=CoreServices");
            println!("cargo:rustc-link-lib=framework=Foundation");
            println!("cargo:rustc-link-lib=framework=Security");
            // OpenSSL
            if let Some(ssl_prefix) = find_openssl_prefix(target_os) {
                println!("cargo:rustc-link-search=native={}/lib", ssl_prefix);
            }
            println!("cargo:rustc-link-lib=ssl");
            println!("cargo:rustc-link-lib=crypto");
            println!("cargo:rustc-link-lib=c++");
            println!("cargo:rustc-link-lib=framework=AVFoundation");
            println!("cargo:rustc-link-lib=framework=CoreMedia");
            println!("cargo:rustc-link-lib=framework=CoreVideo");
            println!("cargo:rustc-link-lib=framework=VideoToolbox");
            println!("cargo:rustc-link-lib=objc");
            // Opus
            if let Some(opus_prefix) = find_opus_prefix(target_os) {
                println!("cargo:rustc-link-search=native={}/lib", opus_prefix);
                println!("cargo:rustc-link-lib=opus");
            }
            // VP8 video codec (libvpx) — only for native builds, not cross-compiled
            if target_arch == std::env::consts::ARCH {
                if let Some(vpx_prefix) = find_lib_prefix("vpx", target_os) {
                    println!("cargo:rustc-link-search=native={}/lib", vpx_prefix);
                }
                println!("cargo:rustc-link-lib=vpx");
            }
        }
        "linux" => {
            println!("cargo:rustc-link-lib=asound");
            println!("cargo:rustc-link-lib=ssl");
            println!("cargo:rustc-link-lib=crypto");
            println!("cargo:rustc-link-lib=opus");
            println!("cargo:rustc-link-lib=vpx");
            println!("cargo:rustc-link-lib=uuid");
            println!("cargo:rustc-link-lib=m");
            println!("cargo:rustc-link-lib=rt");
            println!("cargo:rustc-link-lib=pthread");
            println!("cargo:rustc-link-lib=stdc++");
        }
        "windows" => {
            println!("cargo:rustc-link-lib=winmm");
            println!("cargo:rustc-link-lib=ws2_32");
            println!("cargo:rustc-link-lib=ole32");
            println!("cargo:rustc-link-lib=advapi32");
            println!("cargo:rustc-link-lib=iphlpapi");
            println!("cargo:rustc-link-lib=mswsock");
            println!("cargo:rustc-link-lib=gdi32");
            println!("cargo:rustc-link-lib=user32");
            let is_msvc = env::var("TARGET").unwrap_or_default().contains("msvc");
            if is_msvc {
                // OpenSSL and Opus from vcpkg (static, matching the /MD CRT).
                // PJSIP was only built against them if vcpkg was present when
                // config_site.h was written, so missing vcpkg just means no TLS/Opus.
                if let Some(vcpkg) = vcpkg_installed_dir() {
                    println!(
                        "cargo:rustc-link-search=native={}",
                        vcpkg.join("lib").display()
                    );
                    if vcpkg_has_lib(&vcpkg, "libssl") && vcpkg_has_lib(&vcpkg, "libcrypto") {
                        println!("cargo:rustc-link-lib=static=libssl");
                        println!("cargo:rustc-link-lib=static=libcrypto");
                    }
                    if vcpkg_has_lib(&vcpkg, "opus") {
                        println!("cargo:rustc-link-lib=static=opus");
                        // PJSIP's opus.c embeds `#pragma comment(lib, "libopus.a")`
                        // (GNU naming) into MSVC objects. link.exe must be able to
                        // open that exact filename, so shim a copy of vcpkg's
                        // opus.lib under it.
                        let shim_dir =
                            PathBuf::from(env::var("OUT_DIR").unwrap()).join("msvc-link-shim");
                        fs::create_dir_all(&shim_dir).ok();
                        let shim = shim_dir.join("libopus.a");
                        if !shim.exists() {
                            fs::copy(vcpkg.join("lib").join("opus.lib"), &shim).ok();
                        }
                        println!("cargo:rustc-link-search=native={}", shim_dir.display());
                    }
                }
            } else {
                // MinGW C++ runtime (needed for libyuv)
                println!("cargo:rustc-link-lib=stdc++");
                // OpenSSL and Opus
                if cfg!(target_os = "linux") {
                    // Cross-compiling from Linux
                    let home = env::var("HOME").unwrap_or_else(|_| "/root".to_string());
                    let ssl_dir = env::var("OPENSSL_DIR")
                        .unwrap_or_else(|_| format!("{}/openssl-win64", home));
                    let opus_dir =
                        env::var("OPUS_DIR").unwrap_or_else(|_| format!("{}/opus-win64", home));
                    println!("cargo:rustc-link-search=native={}/lib", ssl_dir);
                    println!("cargo:rustc-link-search=native={}/lib", opus_dir);
                } else {
                    // Native Windows GNU — MSYS2
                    let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
                    println!("cargo:rustc-link-search=native={}/mingw64/lib", msys2);
                }
                println!("cargo:rustc-link-lib=ssl");
                println!("cargo:rustc-link-lib=crypto");
                println!("cargo:rustc-link-lib=opus");
            }
            println!("cargo:rustc-link-lib=crypt32");
        }
        "android" => {
            println!("cargo:rustc-link-lib=OpenSLES");
            println!("cargo:rustc-link-lib=log");
            println!("cargo:rustc-link-lib=android");
            println!("cargo:rustc-link-lib=m");
        }
        "ios" => {
            println!("cargo:rustc-link-lib=framework=AudioToolbox");
            println!("cargo:rustc-link-lib=framework=AudioUnit");
            println!("cargo:rustc-link-lib=framework=CoreAudio");
            println!("cargo:rustc-link-lib=framework=CoreFoundation");
            println!("cargo:rustc-link-lib=framework=CoreMedia");
            println!("cargo:rustc-link-lib=framework=CoreVideo");
            println!("cargo:rustc-link-lib=framework=AVFoundation");
            println!("cargo:rustc-link-lib=framework=Foundation");
            println!("cargo:rustc-link-lib=framework=Security");
            println!("cargo:rustc-link-lib=framework=UIKit");
        }
        _ => {}
    }
}

/// Generate Rust bindings from wrapper.h using bindgen
fn generate_bindings(pj_src_dir: &Path, out_dir: &Path, _target_os: &str) {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wrapper_h = manifest_dir.join("wrapper.h");

    let mut builder = bindgen::Builder::default()
        .header(wrapper_h.to_str().unwrap())
        .clang_arg("-DPJ_IS_LITTLE_ENDIAN=1")
        .clang_arg("-DPJ_IS_BIG_ENDIAN=0");

    if _target_os == "windows" {
        // Windows: PJSIP was built under MSYS2 (which has unistd.h), but bindgen
        // uses MSVC's clang which does NOT have Unix headers. Skip PJ_AUTOCONF
        // entirely and set all platform defines manually so the headers use
        // winsock2.h instead of sys/socket.h + unistd.h.
        builder = builder
            .clang_arg("-DPJ_WIN32=1")
            .clang_arg("-DPJ_WIN64=1")
            .clang_arg("-D_WIN32")
            .clang_arg("-D_WIN64")
            .clang_arg("-DPJMEDIA_AUDIO_DEV_HAS_WMME=1")
            .clang_arg("-DPJ_HAS_WINSOCK2_H=1")
            .clang_arg("-DPJ_HAS_UNISTD_H=0")
            .clang_arg("-DPJ_HAS_SYS_SOCKET_H=0")
            .clang_arg("-DPJ_HAS_SYS_SELECT_H=0")
            .clang_arg("-DPJ_HAS_ARPA_INET_H=0")
            .clang_arg("-DPJ_HAS_NETDB_H=0")
            .clang_arg("-DPJ_HAS_NETINET_IN_H=0")
            .clang_arg("-DPJ_HAS_NETINET_TCP_H=0")
            .clang_arg("-DPJ_HAS_IFADDRS_H=0")
            .clang_arg("-DPJ_HAS_SYS_FILIO_H=0")
            .clang_arg("-DPJ_HAS_SYS_SOCKIO_H=0")
            .clang_arg("-DPJ_HAS_ERRNO_H=1")
            .clang_arg("-DPJ_HAS_STDINT_H=1")
            .clang_arg("-DPJ_HAS_STRING_H=1")
            .clang_arg("-DPJ_HAS_STDDEF_H=1");
    } else if _target_os == "android" {
        // Android: use autoconf config but point clang to NDK sysroot
        builder = builder.clang_arg("-DPJ_AUTOCONF=1");
        if let Ok(sysroot) = env::var("PALE_ANDROID_SYSROOT") {
            builder = builder
                .clang_arg(format!("--sysroot={}", sysroot))
                .clang_arg("--target=aarch64-linux-android24");
        }
    } else {
        // Unix: use autoconf-generated config_site.h
        builder = builder.clang_arg("-DPJ_AUTOCONF=1");
    }

    let bindings = builder
        // Include paths for all PJSIP sub-libraries
        .clang_arg(format!("-I{}/pjlib/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjlib-util/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjnath/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjmedia/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjsip/include", pj_src_dir.display()))
        // Allowlists — only generate bindings for what we need
        .allowlist_function("pjsua_.*")
        .allowlist_function("pjmedia_tonegen_.*")
        .allowlist_function("pjmedia_aud_dev_.*")
        .allowlist_function("pj_init")
        .allowlist_function("pj_shutdown")
        .allowlist_function("pj_str")
        .allowlist_function("pj_pool_release")
        .allowlist_function("pj_thread_register")
        .allowlist_function("pj_thread_is_registered")
        .allowlist_type("pjsua_.*")
        .allowlist_type("pjsip_status_code")
        .allowlist_type("pjsip_event")
        .allowlist_type("pjsip_rx_data")
        .allowlist_type("pjsip_transaction")
        .allowlist_type("pjmedia_port")
        .allowlist_type("pjmedia_tonegen.*")
        .allowlist_type("pjmedia_aud_dev_info")
        .allowlist_type("pjmedia_aud_param")
        .allowlist_type("pjmedia_dir")
        .allowlist_type("pj_str_t")
        .allowlist_type("pj_status_t")
        .allowlist_type("pj_bool_t")
        .allowlist_type("pj_pool_t")
        .allowlist_type("pj_thread_t")
        .allowlist_type("pj_thread_desc")
        .allowlist_var("PJ_SUCCESS")
        .allowlist_var("PJSIP_SC_.*")
        .allowlist_var("PJSUA_.*")
        .allowlist_var("PJMEDIA_DIR_.*")
        .allowlist_var("PJMEDIA_AUD_DEV_CAP_.*")
        // Size and derive settings
        .derive_debug(true)
        .derive_default(true)
        .size_t_is_usize(true)
        // Layout tests can fail cross-platform; skip them
        .layout_tests(false)
        .generate()
        .expect("bindgen failed to generate PJSIP bindings");

    let out_path = out_dir.join("bindings.rs");
    bindings
        .write_to_file(&out_path)
        .expect("Failed to write bindings.rs");

    println!(
        "cargo:warning=Generated PJSIP bindings at {}",
        out_path.display()
    );
}

// ─── Helper functions ───

/// Find PJSIP library directories (they contain platform-suffixed .a files)
fn find_pjsip_lib_dirs(pj_src_dir: &Path) -> Vec<PathBuf> {
    let subdirs = [
        "pjlib/lib",
        "pjlib-util/lib",
        "pjnath/lib",
        "pjmedia/lib",
        "pjsip/lib",
        "third_party/lib",
    ];

    subdirs
        .iter()
        .map(|sub| pj_src_dir.join(sub))
        .filter(|p| p.exists())
        .collect()
}

/// Find OpenSSL install prefix
fn find_openssl_prefix(target_os: &str) -> Option<String> {
    // Try pkg-config first
    if let Ok(output) = Command::new("pkg-config")
        .args(["--variable=prefix", "openssl"])
        .output()
    {
        if output.status.success() {
            let prefix = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !prefix.is_empty() {
                return Some(prefix);
            }
        }
    }

    // Platform-specific defaults
    match target_os {
        "macos" => {
            // Homebrew paths
            for path in &[
                "/opt/homebrew/opt/openssl@3",
                "/opt/homebrew/opt/openssl",
                "/usr/local/opt/openssl@3",
                "/usr/local/opt/openssl",
            ] {
                if Path::new(path).exists() {
                    return Some(path.to_string());
                }
            }
        }
        "linux" => {
            if Path::new("/usr/include/openssl").exists() {
                return Some("/usr".to_string());
            }
        }
        _ => {}
    }

    None
}

/// Find Opus install prefix
fn find_lib_prefix(name: &str, target_os: &str) -> Option<String> {
    if let Ok(output) = Command::new("pkg-config")
        .args(["--variable=prefix", name])
        .output()
    {
        if output.status.success() {
            let prefix = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !prefix.is_empty() {
                return Some(prefix);
            }
        }
    }
    if target_os == "macos" {
        for path in &[
            format!("/opt/homebrew/opt/{name}"),
            format!("/usr/local/opt/{name}"),
        ] {
            if Path::new(path).exists() {
                return Some(path.clone());
            }
        }
    }
    None
}

fn find_opus_prefix(target_os: &str) -> Option<String> {
    // Try pkg-config
    if let Ok(output) = Command::new("pkg-config")
        .args(["--variable=prefix", "opus"])
        .output()
    {
        if output.status.success() {
            let prefix = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !prefix.is_empty() {
                return Some(prefix);
            }
        }
    }

    // Homebrew paths on macOS
    if target_os == "macos" {
        for path in &["/opt/homebrew/opt/opus", "/usr/local/opt/opus"] {
            if Path::new(path).exists() {
                return Some(path.to_string());
            }
        }
    }

    None
}

/// Detect the platform suffix PJSIP uses for its library names.
/// Looks for `libpj-<suffix>.a` in pjlib/lib since "pj" is unambiguous.
fn detect_platform_suffix(lib_dirs: &[PathBuf]) -> Option<String> {
    for dir in lib_dirs {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                // Match libpj-<something>.a but not libpjsip or libpjlib etc.
                if name.starts_with("libpj-") && name.ends_with(".a") {
                    // "libpj-arm-apple-darwin24.6.0.a" -> "arm-apple-darwin24.6.0"
                    let suffix = &name["libpj-".len()..name.len() - ".a".len()];
                    return Some(suffix.to_string());
                }
            }
        }
    }
    None
}
