use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Pinned PJSIP version
const PJSIP_VERSION: &str = "2.14.1";
const PJSIP_TARBALL: &str = "pjproject-2.14.1.tar.gz";
const PJSIP_URL: &str =
    "https://github.com/pjsip/pjproject/archive/refs/tags/2.14.1.tar.gz";
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=wrapper.h");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let pj_src_dir = out_dir.join(format!("pjproject-{}", PJSIP_VERSION));

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();

    // Step 1: Download PJSIP source if not present
    if !pj_src_dir.exists() {
        download_pjsip(&out_dir);
    }

    // Step 2: Build PJSIP if not already built
    // Check for the existence of the core libpj to avoid expensive rebuilds
    let pj_lib_dir = pj_src_dir.join("pjlib/lib");
    let already_built = pj_lib_dir.exists()
        && fs::read_dir(&pj_lib_dir)
            .map(|entries| entries.count() > 0)
            .unwrap_or(false);

    if !already_built {
        write_config_site(&pj_src_dir, &target_os);
        build_pjsip(&pj_src_dir, &target_os, &target_arch);
    } else {
        eprintln!("cargo:warning=PJSIP already built, skipping compilation.");
    }

    // Step 3: Emit linker directives
    emit_link_directives(&pj_src_dir, &target_os);

    // Step 4: Generate Rust bindings via bindgen
    generate_bindings(&pj_src_dir, &out_dir, &target_os);
}

/// Download and extract PJSIP source tarball
fn download_pjsip(out_dir: &Path) {
    let tarball_path = out_dir.join(PJSIP_TARBALL);

    if !tarball_path.exists() {
        eprintln!("cargo:warning=Downloading PJSIP {}...", PJSIP_VERSION);
        let status = Command::new("curl")
            .args([
                "-L",
                "-o",
                tarball_path.to_str().unwrap(),
                PJSIP_URL,
            ])
            .status()
            .expect("Failed to run curl. Is curl installed?");
        assert!(status.success(), "Failed to download PJSIP tarball");
    }

    eprintln!("cargo:warning=Extracting PJSIP...");
    let status = Command::new("tar")
        .args(["xzf", tarball_path.to_str().unwrap()])
        .current_dir(out_dir)
        .status()
        .expect("Failed to run tar");
    assert!(status.success(), "Failed to extract PJSIP tarball");
}

/// Write config_site.h with platform-appropriate defines
fn write_config_site(pj_src_dir: &Path, target_os: &str) {
    let config_path = pj_src_dir.join("pjlib/include/pj/config_site.h");
    let mut config = String::new();

    config.push_str("/* Auto-generated by pjsip-sys build.rs */\n");
    config.push_str("#define PJ_HAS_IPV6 1\n");
    config.push_str("#define PJMEDIA_HAS_SRTP 1\n");
    config.push_str("#define PJMEDIA_HAS_VIDEO 1\n");
    config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_NULL 1\n");
    config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 0\n");
    config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_WMME 0\n");

    match target_os {
        "macos" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_DARWIN 1\n");
        }
        "linux" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_ALSA 1\n");
        }
        "windows" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_WMME 1\n");
        }
        "android" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_OPENSL 1\n");
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_ANDROID 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_ANDROID 1\n");
            config.push_str("#define PJ_ANDROID 1\n");
        }
        "ios" => {
            config.push_str("#define PJMEDIA_AUDIO_DEV_HAS_COREAUDIO 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_IOS 1\n");
            config.push_str("#define PJMEDIA_VIDEO_DEV_HAS_DARWIN 1\n");
        }
        _ => {}
    }

    fs::write(&config_path, config)
        .unwrap_or_else(|e| panic!("Failed to write config_site.h: {}", e));
}

/// Configure and build PJSIP from source
fn build_pjsip(pj_src_dir: &Path, target_os: &str, target_arch: &str) {
    eprintln!(
        "cargo:warning=Building PJSIP {} for {}/{}...",
        PJSIP_VERSION, target_os, target_arch
    );

    // Determine OpenSSL path
    let openssl_prefix = find_openssl_prefix(target_os);

    // Build configure arguments
    let mut configure_args = vec![
        "./configure".to_string(),
        "--enable-shared=no".to_string(),
    ];

    // Windows: MSYS2/MinGW build needs explicit host and build triples
    // (config.guess from 2012 cannot recognize MSYS_NT systems)
    if target_os == "windows" {
        configure_args.push("--host=x86_64-w64-mingw32".to_string());
        configure_args.push("--build=x86_64-w64-mingw32".to_string());
    }

    // Android cross-compilation
    if target_os == "android" {
        let ndk_home = env::var("NDK_HOME")
            .or_else(|_| env::var("ANDROID_NDK_HOME"))
            .unwrap_or_else(|_| {
                let android_home = env::var("ANDROID_HOME")
                    .expect("NDK_HOME or ANDROID_HOME must be set for Android builds");
                // Find the latest NDK version
                let ndk_dir = Path::new(&android_home).join("ndk");
                if let Ok(entries) = fs::read_dir(&ndk_dir) {
                    let mut versions: Vec<String> = entries
                        .filter_map(|e| e.ok())
                        .filter_map(|e| e.file_name().into_string().ok())
                        .collect();
                    versions.sort();
                    if let Some(latest) = versions.last() {
                        return ndk_dir.join(latest).to_string_lossy().to_string();
                    }
                }
                panic!("No NDK found in {}", ndk_dir.display());
            });

        let host_tag = if cfg!(target_os = "macos") {
            "darwin-x86_64"
        } else if cfg!(target_os = "linux") {
            "linux-x86_64"
        } else {
            "windows-x86_64"
        };

        let toolchain = format!("{}/toolchains/llvm/prebuilt/{}", ndk_home, host_tag);
        let api_level = "24"; // Android 7.0 minimum

        let android_target = match target_arch {
            "aarch64" => "aarch64-linux-android",
            "arm" => "armv7a-linux-androideabi",
            "x86_64" => "x86_64-linux-android",
            "x86" => "i686-linux-android",
            _ => panic!("Unsupported Android arch: {}", target_arch),
        };

        let cc = format!("{}/bin/{}{}-clang", toolchain, android_target, api_level);
        configure_args.push(format!("--host={}", android_target));
        configure_args.push(format!("CC={}", cc));
        configure_args.push(format!("CXX={}++", cc));
        configure_args.push(format!("AR={}/bin/llvm-ar", toolchain));
        configure_args.push(format!("RANLIB={}/bin/llvm-ranlib", toolchain));
    }

    // iOS cross-compilation
    if target_os == "ios" {
        let ios_target = match target_arch {
            "aarch64" => "arm64-apple-ios",
            "x86_64" => "x86_64-apple-ios-simulator",
            _ => panic!("Unsupported iOS arch: {}", target_arch),
        };

        let sdk = if target_arch == "x86_64" { "iphonesimulator" } else { "iphoneos" };
        let sdk_path_output = Command::new("xcrun")
            .args(["--sdk", sdk, "--show-sdk-path"])
            .output()
            .expect("Failed to find iOS SDK path");
        let sdk_path = String::from_utf8_lossy(&sdk_path_output.stdout).trim().to_string();

        let min_ios = "15.0";
        configure_args.push(format!("--host={}", ios_target));
        configure_args.push(format!("CFLAGS=-isysroot {} -miphoneos-version-min={} -arch {} -fembed-bitcode",
            sdk_path, min_ios, if target_arch == "aarch64" { "arm64" } else { "x86_64" }));
    }

    if target_os == "windows" {
        // Use MSYS2 MinGW OpenSSL and Opus
        let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
        // Convert Windows path to MSYS2 path for configure
        let msys2_unix = msys2.replace('\\', "/").replace("C:", "/c");
        configure_args.push(format!("--with-ssl={}/mingw64", msys2_unix));
        configure_args.push(format!("--with-opus={}/mingw64", msys2_unix));
    } else {
        if let Some(ref ssl_prefix) = openssl_prefix {
            configure_args.push(format!("--with-ssl={}", ssl_prefix));
        }
        if let Some(opus_prefix) = find_opus_prefix(target_os) {
            configure_args.push(format!("--with-opus={}", opus_prefix));
        }
    }


    // Set CFLAGS
    let cflags = format!(
        "-O2 -fPIC -DPJMEDIA_HAS_SRTP=1 -DPJ_HAS_IPV6=1 {}",
        match target_os {
            "macos" => "-mmacosx-version-min=11.0",
            "android" => "-DPJ_ANDROID=1",
            _ => "",
        }
    );

    // Determine shell and make commands
    // On Windows, use MSYS2 bash/make (pre-installed on GitHub Actions runners)
    let (sh_cmd, make_cmd) = if target_os == "windows" {
        let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
        let sh = format!("{}/usr/bin/bash.exe", msys2);
        let mk = format!("{}/usr/bin/make.exe", msys2);
        (sh, mk)
    } else {
        ("sh".to_string(), "make".to_string())
    };

    // Run configure
    let status = Command::new(&sh_cmd)
        .arg("-c")
        .arg(&configure_args.join(" "))
        .env("CFLAGS", &cflags)
        .current_dir(pj_src_dir)
        .status()
        .expect("Failed to run PJSIP configure");
    assert!(status.success(), "PJSIP configure failed");

    let num_jobs = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    // Run make dep
    let status = Command::new(&make_cmd)
        .args(["dep", &format!("-j{}", num_jobs)])
        .current_dir(pj_src_dir)
        .status()
        .expect("Failed to run make dep");
    assert!(status.success(), "PJSIP make dep failed");

    // Run make
    let status = Command::new(&make_cmd)
        .arg(&format!("-j{}", num_jobs))
        .current_dir(pj_src_dir)
        .status()
        .expect("Failed to run make");
    assert!(status.success(), "PJSIP make failed");

    eprintln!("cargo:warning=PJSIP build complete.");
}

/// Emit cargo:rustc-link-lib and cargo:rustc-link-search directives
fn emit_link_directives(pj_src_dir: &Path, target_os: &str) {
    let lib_dirs = find_pjsip_lib_dirs(pj_src_dir);

    // PJSIP names its static libs with the host triple suffix, e.g.:
    //   libpj-arm-apple-darwin24.6.0.a
    //   libpjsip-ua-arm-apple-darwin24.6.0.a
    // Cargo's `rustc-link-lib=static=pj` looks for `libpj.a`.
    // Detect the suffix from libpj-*.a (which is unambiguous) then strip it from all libs.
    let platform_suffix = detect_platform_suffix(&lib_dirs);
    if let Some(ref suffix) = platform_suffix {
        eprintln!("cargo:warning=Detected PJSIP platform suffix: -{}", suffix);
        for dir in &lib_dirs {
            if let Ok(entries) = fs::read_dir(dir) {
                for entry in entries.flatten() {
                    let name = entry.file_name().to_string_lossy().to_string();
                    let suffixed = format!("-{}.a", suffix);
                    if name.starts_with("lib") && name.ends_with(&suffixed) {
                        let base = &name[..name.len() - suffixed.len()];
                        let unsuffixed = format!("{}.a", base);
                        let dest = dir.join(&unsuffixed);
                        if !dest.exists() {
                            let _ = fs::copy(entry.path(), &dest);
                        }
                    }
                }
            }
        }
    }

    for dir in &lib_dirs {
        println!("cargo:rustc-link-search=native={}", dir.display());
    }

    // Link PJSIP static libraries — ORDER MATTERS (highest-level first)
    let pjsip_libs = [
        "pjsua",
        "pjsip-ua",
        "pjsip-simple",
        "pjsip",
        "pjmedia-codec",
        "pjmedia",
        "pjmedia-audiodev",
        "pjmedia-videodev",
        "pjsdp",
        "pjnath",
        "pjlib-util",
        "pj",
        "srtp",
        "resample",
        "g7221codec",
        "ilbccodec",
        "speex",
        "gsmcodec",
        "webrtc",
        "yuv",
    ];

    for lib in &pjsip_libs {
        let found = lib_dirs.iter().any(|dir| dir.join(format!("lib{}.a", lib)).exists());
        if found {
            println!("cargo:rustc-link-lib=static={}", lib);
        }
    }

    // Platform system libraries
    match target_os {
        "macos" => {
            println!("cargo:rustc-link-lib=framework=AudioToolbox");
            println!("cargo:rustc-link-lib=framework=AudioUnit");
            println!("cargo:rustc-link-lib=framework=CoreAudio");
            println!("cargo:rustc-link-lib=framework=CoreFoundation");
            println!("cargo:rustc-link-lib=framework=CoreServices");
            println!("cargo:rustc-link-lib=framework=Foundation");
            println!("cargo:rustc-link-lib=framework=Security");
            // OpenSSL
            if let Some(ssl_prefix) = find_openssl_prefix(target_os) {
                println!("cargo:rustc-link-search=native={}/lib", ssl_prefix);
            }
            println!("cargo:rustc-link-lib=ssl");
            println!("cargo:rustc-link-lib=crypto");
            println!("cargo:rustc-link-lib=c++");
            println!("cargo:rustc-link-lib=framework=AVFoundation");
            println!("cargo:rustc-link-lib=framework=CoreMedia");
            println!("cargo:rustc-link-lib=framework=CoreVideo");
            println!("cargo:rustc-link-lib=framework=VideoToolbox");
            println!("cargo:rustc-link-lib=objc");
            // Opus
            if let Some(opus_prefix) = find_opus_prefix(target_os) {
                println!("cargo:rustc-link-search=native={}/lib", opus_prefix);
                println!("cargo:rustc-link-lib=opus");
            }
        }
        "linux" => {
            println!("cargo:rustc-link-lib=asound");
            println!("cargo:rustc-link-lib=ssl");
            println!("cargo:rustc-link-lib=crypto");
            println!("cargo:rustc-link-lib=opus");
            println!("cargo:rustc-link-lib=uuid");
            println!("cargo:rustc-link-lib=m");
            println!("cargo:rustc-link-lib=rt");
            println!("cargo:rustc-link-lib=pthread");
            println!("cargo:rustc-link-lib=stdc++");
        }
        "windows" => {
            println!("cargo:rustc-link-lib=winmm");
            println!("cargo:rustc-link-lib=ws2_32");
            println!("cargo:rustc-link-lib=ole32");
            println!("cargo:rustc-link-lib=advapi32");
            println!("cargo:rustc-link-lib=iphlpapi");
            println!("cargo:rustc-link-lib=mswsock");
            println!("cargo:rustc-link-lib=gdi32");
            println!("cargo:rustc-link-lib=user32");
            println!("cargo:rustc-link-lib=stdc++");
            // OpenSSL from MSYS2
            let msys2 = env::var("MSYS2_PATH").unwrap_or_else(|_| "C:\\msys64".to_string());
            println!("cargo:rustc-link-search=native={}/mingw64/lib", msys2);
            println!("cargo:rustc-link-lib=ssl");
            println!("cargo:rustc-link-lib=crypto");
            println!("cargo:rustc-link-lib=opus");
        }
        "android" => {
            println!("cargo:rustc-link-lib=OpenSLES");
            println!("cargo:rustc-link-lib=log");
            println!("cargo:rustc-link-lib=android");
            println!("cargo:rustc-link-lib=m");
        }
        "ios" => {
            println!("cargo:rustc-link-lib=framework=AudioToolbox");
            println!("cargo:rustc-link-lib=framework=AudioUnit");
            println!("cargo:rustc-link-lib=framework=CoreAudio");
            println!("cargo:rustc-link-lib=framework=CoreFoundation");
            println!("cargo:rustc-link-lib=framework=CoreMedia");
            println!("cargo:rustc-link-lib=framework=CoreVideo");
            println!("cargo:rustc-link-lib=framework=AVFoundation");
            println!("cargo:rustc-link-lib=framework=Foundation");
            println!("cargo:rustc-link-lib=framework=Security");
            println!("cargo:rustc-link-lib=framework=UIKit");
        }
        _ => {}
    }
}

/// Generate Rust bindings from wrapper.h using bindgen
fn generate_bindings(pj_src_dir: &Path, out_dir: &Path, _target_os: &str) {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wrapper_h = manifest_dir.join("wrapper.h");

    let bindings = bindgen::Builder::default()
        .header(wrapper_h.to_str().unwrap())
        // Defines needed for PJSIP headers (use autoconf-generated config)
        .clang_arg("-DPJ_AUTOCONF=1")
        .clang_arg("-DPJ_IS_LITTLE_ENDIAN=1")
        .clang_arg("-DPJ_IS_BIG_ENDIAN=0")
        // Include paths for all PJSIP sub-libraries
        .clang_arg(format!("-I{}/pjlib/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjlib-util/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjnath/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjmedia/include", pj_src_dir.display()))
        .clang_arg(format!("-I{}/pjsip/include", pj_src_dir.display()))
        // Allowlists — only generate bindings for what we need
        .allowlist_function("pjsua_.*")
        .allowlist_function("pjmedia_tonegen_.*")
        .allowlist_function("pjmedia_aud_dev_.*")
        .allowlist_function("pj_init")
        .allowlist_function("pj_shutdown")
        .allowlist_function("pj_str")
        .allowlist_function("pj_pool_release")
        .allowlist_function("pj_thread_register")
        .allowlist_function("pj_thread_is_registered")
        .allowlist_type("pjsua_.*")
        .allowlist_type("pjsip_status_code")
        .allowlist_type("pjsip_event")
        .allowlist_type("pjsip_rx_data")
        .allowlist_type("pjsip_transaction")
        .allowlist_type("pjmedia_port")
        .allowlist_type("pjmedia_tonegen.*")
        .allowlist_type("pjmedia_aud_dev_info")
        .allowlist_type("pjmedia_aud_param")
        .allowlist_type("pjmedia_dir")
        .allowlist_type("pj_str_t")
        .allowlist_type("pj_status_t")
        .allowlist_type("pj_bool_t")
        .allowlist_type("pj_pool_t")
        .allowlist_type("pj_thread_t")
        .allowlist_type("pj_thread_desc")
        .allowlist_var("PJ_SUCCESS")
        .allowlist_var("PJSIP_SC_.*")
        .allowlist_var("PJSUA_.*")
        .allowlist_var("PJMEDIA_DIR_.*")
        .allowlist_var("PJMEDIA_AUD_DEV_CAP_.*")
        // Size and derive settings
        .derive_debug(true)
        .derive_default(true)
        .size_t_is_usize(true)
        // Layout tests can fail cross-platform; skip them
        .layout_tests(false)
        .generate()
        .expect("bindgen failed to generate PJSIP bindings");

    let out_path = out_dir.join("bindings.rs");
    bindings
        .write_to_file(&out_path)
        .expect("Failed to write bindings.rs");

    eprintln!(
        "cargo:warning=Generated PJSIP bindings at {}",
        out_path.display()
    );
}

// ─── Helper functions ───

/// Find PJSIP library directories (they contain platform-suffixed .a files)
fn find_pjsip_lib_dirs(pj_src_dir: &Path) -> Vec<PathBuf> {
    let subdirs = [
        "pjlib/lib",
        "pjlib-util/lib",
        "pjnath/lib",
        "pjmedia/lib",
        "pjsip/lib",
        "third_party/lib",
    ];

    subdirs
        .iter()
        .map(|sub| pj_src_dir.join(sub))
        .filter(|p| p.exists())
        .collect()
}

/// Find OpenSSL install prefix
fn find_openssl_prefix(target_os: &str) -> Option<String> {
    // Try pkg-config first
    if let Ok(output) = Command::new("pkg-config")
        .args(["--variable=prefix", "openssl"])
        .output()
    {
        if output.status.success() {
            let prefix = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !prefix.is_empty() {
                return Some(prefix);
            }
        }
    }

    // Platform-specific defaults
    match target_os {
        "macos" => {
            // Homebrew paths
            for path in &[
                "/opt/homebrew/opt/openssl@3",
                "/opt/homebrew/opt/openssl",
                "/usr/local/opt/openssl@3",
                "/usr/local/opt/openssl",
            ] {
                if Path::new(path).exists() {
                    return Some(path.to_string());
                }
            }
        }
        "linux" => {
            if Path::new("/usr/include/openssl").exists() {
                return Some("/usr".to_string());
            }
        }
        _ => {}
    }

    None
}

/// Find Opus install prefix
fn find_opus_prefix(target_os: &str) -> Option<String> {
    // Try pkg-config
    if let Ok(output) = Command::new("pkg-config")
        .args(["--variable=prefix", "opus"])
        .output()
    {
        if output.status.success() {
            let prefix = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !prefix.is_empty() {
                return Some(prefix);
            }
        }
    }

    // Homebrew paths on macOS
    if target_os == "macos" {
        for path in &[
            "/opt/homebrew/opt/opus",
            "/usr/local/opt/opus",
        ] {
            if Path::new(path).exists() {
                return Some(path.to_string());
            }
        }
    }

    None
}

/// Detect the platform suffix PJSIP uses for its library names.
/// Looks for `libpj-<suffix>.a` in pjlib/lib since "pj" is unambiguous.
fn detect_platform_suffix(lib_dirs: &[PathBuf]) -> Option<String> {
    for dir in lib_dirs {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                // Match libpj-<something>.a but not libpjsip or libpjlib etc.
                if name.starts_with("libpj-") && name.ends_with(".a") {
                    // "libpj-arm-apple-darwin24.6.0.a" -> "arm-apple-darwin24.6.0"
                    let suffix = &name["libpj-".len()..name.len() - ".a".len()];
                    return Some(suffix.to_string());
                }
            }
        }
    }
    None
}
