ALTER TABLE user_call_settings
  ADD COLUMN IF NOT EXISTS allow_private_calls BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_external_calls BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_call_forwarding BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_call_recording BOOLEAN NOT NULL DEFAULT TRUE;
