#!/bin/sh
# Generate a .env file with the secrets pale-server's docker-compose requires.
# Safe to run once per deployment; refuses to overwrite an existing .env.
set -eu

cd "$(dirname "$0")/.."

if [ -f .env ]; then
    echo "error: .env already exists — remove it first if you really want new secrets." >&2
    echo "       (Rotating secrets invalidates existing sessions and the storage key" >&2
    echo "        makes previously stored files unreadable.)" >&2
    exit 1
fi

umask 077
cat > .env <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# See .env.example for optional settings and docs/deploy/PRODUCTION.md for prod.

# Required secrets
PALE_SERVER_TOKEN=$(openssl rand -base64 32)
PALE_ADMIN_PASSWORD=$(openssl rand -base64 32)
PALE_STORAGE_KEY=$(openssl rand -base64 32)
POSTGRES_PASSWORD=$(openssl rand -hex 32)
TURN_SECRET=$(openssl rand -hex 32)
NATS_TOKEN=$(openssl rand -hex 32)

# SIP / TURN — fill these before docker-compose.prod.yml
#PALE_PUBLIC_HOSTNAME=pale.example.com
#PALE_SIP_EXTERNAL_ADDR=pale.example.com:5060
#PALE_SIP_TLS_EXTERNAL_ADDR=pale.example.com:5061
#PALE_TURN_SERVER=turn:pale.example.com:3478
#TURN_EXTERNAL_IP=
#CERTS_DIR=./certs

# Safe defaults for Docker (udp-parser = built-in registrar/PBX)
PALE_SIP_BACKEND=udp-parser
PALE_SIP_SRTP=true
PALE_SIP_TCP=true
PALE_SIP_UDP=false
EOF

echo "Wrote .env with secrets (PALE_SERVER_TOKEN, PALE_ADMIN_PASSWORD, PALE_STORAGE_KEY,"
echo "POSTGRES_PASSWORD, TURN_SECRET, NATS_TOKEN) and secure SIP defaults."
echo "Admin login: user 'admin' (override with PALE_ADMIN_USERNAME), password is PALE_ADMIN_PASSWORD in .env."
echo ""
echo "Local lab:   docker compose up -d && curl http://localhost:8090/health"
echo "Production:  edit .env hostnames + place certs in ./certs, then:"
echo "             docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
echo "See docs/deploy/PRODUCTION.md"
