#!/bin/sh
# Generate a .env file with the secrets pale-server's docker-compose requires.
# Safe to run once per deployment; refuses to overwrite an existing .env.
set -eu

cd "$(dirname "$0")/.."

if [ -f .env ]; then
    echo "error: .env already exists — remove it first if you really want new secrets." >&2
    echo "       (Rotating secrets invalidates existing sessions and the storage key" >&2
    echo "        makes previously stored files unreadable.)" >&2
    exit 1
fi

umask 077
cat > .env <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# See .env.example for optional settings.
PALE_SERVER_TOKEN=$(openssl rand -base64 32)
PALE_ADMIN_PASSWORD=$(openssl rand -base64 32)
PALE_STORAGE_KEY=$(openssl rand -base64 32)
POSTGRES_PASSWORD=$(openssl rand -hex 32)
TURN_SECRET=$(openssl rand -hex 32)
EOF

echo "Wrote .env with PALE_SERVER_TOKEN, PALE_ADMIN_PASSWORD, PALE_STORAGE_KEY, POSTGRES_PASSWORD, TURN_SECRET."
echo "Admin login: user 'admin' (override with PALE_ADMIN_USERNAME), password is PALE_ADMIN_PASSWORD in .env."
echo "Next: docker compose up -d && curl http://localhost:8090/health"
