#!/usr/bin/env bash
set -euo pipefail

REPO_BASE_URL="${PALE_REPO_BASE_URL:-https://drcpbx.com}"
ENV_DIR="/etc/pale-server"
ENV_FILE="$ENV_DIR/pale-server.env"
DATA_DIR="/var/lib/pale-server"
SERVICE_NAME="pale-server"

die() {
  echo "error: $*" >&2
  exit 1
}

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    die "run this installer as root, for example: sudo $0"
  fi
}

random_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

env_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

prompt_default() {
  local label="$1"
  local default="$2"
  local value
  read -r -p "$label [$default]: " value
  printf '%s\n' "${value:-$default}"
}

prompt_secret() {
  local first second
  while true; do
    read -r -s -p "Pale Server admin password, 24+ characters: " first
    echo
    read -r -s -p "Confirm admin password: " second
    echo
    if [ "$first" != "$second" ]; then
      echo "passwords did not match"
      continue
    fi
    if [ "${#first}" -lt 24 ]; then
      echo "password must be at least 24 characters"
      continue
    fi
    printf '%s\n' "$first"
    return
  done
}

detect_os() {
  [ -r /etc/os-release ] || die "cannot detect Linux distribution"
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID_LIKE:-} ${ID:-}" in
    *debian*|*ubuntu*)
      echo "apt"
      ;;
    *rhel*|*fedora*|*centos*|*rocky*|*almalinux*)
      echo "dnf"
      ;;
    *)
      die "unsupported distribution: ${PRETTY_NAME:-unknown}. Use Debian/Ubuntu or RHEL-compatible Linux."
      ;;
  esac
}

install_from_apt() {
  apt-get update
  apt-get install -y ca-certificates curl gnupg openssl
  install -d -m 0755 /usr/share/keyrings
  rm -f /usr/share/keyrings/pale-server.gpg
  curl -fsSL "$REPO_BASE_URL/pale-repo.asc" | gpg --dearmor -o /usr/share/keyrings/pale-server.gpg
  cat >/etc/apt/sources.list.d/pale-server.list <<EOF
deb [signed-by=/usr/share/keyrings/pale-server.gpg] $REPO_BASE_URL/apt stable main
EOF
  apt-get update
  apt-get install -y pale-server
}

install_from_dnf() {
  if command -v dnf >/dev/null 2>&1; then
    dnf install -y curl openssl
    install -d -m 0755 /etc/yum.repos.d
    curl -fsSL "$REPO_BASE_URL/rpm/pale-server.repo" -o /etc/yum.repos.d/pale-server.repo
    dnf install -y pale-server
  elif command -v yum >/dev/null 2>&1; then
    yum install -y curl openssl
    install -d -m 0755 /etc/yum.repos.d
    curl -fsSL "$REPO_BASE_URL/rpm/pale-server.repo" -o /etc/yum.repos.d/pale-server.repo
    yum install -y pale-server
  else
    die "dnf/yum was not found"
  fi
}

server_binary() {
  if command -v pale-server >/dev/null 2>&1; then
    command -v pale-server
    return
  fi
  for path in /usr/local/bin/pale-server /usr/bin/pale-server /opt/pale-server/pale-server; do
    if [ -x "$path" ]; then
      echo "$path"
      return
    fi
  done
  die "pale-server binary was not found after package install"
}

write_env() {
  local http_addr="$1"
  local admin_user="$2"
  local admin_password="$3"
  local sip_backend="$4"

  install -d -m 0750 "$ENV_DIR" "$DATA_DIR"
  cat >"$ENV_FILE" <<EOF
# Pale Server local configuration
# Generated by scripts/install-pale-server.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# This file contains local secrets. Do not publish it.
# Production guide: docs/deploy/PRODUCTION.md and docs/deploy/linux.md
PALE_ADMIN_USERNAME=$(env_quote "$admin_user")
PALE_ADMIN_PASSWORD=$(env_quote "$admin_password")
PALE_DATA_DIR=$(env_quote "$DATA_DIR")
PALE_HTTP_ADDR=$(env_quote "$http_addr")
PALE_LOG_JSON=true
PALE_SERVER_TOKEN=$(env_quote "$(random_secret)")
PALE_SIP_BACKEND=$(env_quote "$sip_backend")
PALE_SIP_TCP=true
PALE_SIP_UDP=false
PALE_SIP_SRTP=true
PALE_STORAGE_KEY=$(env_quote "$(random_secret)")
# Uncomment and set for production calling (see docs/deploy/linux.md):
#PALE_SIP_TLS=true
#PALE_SIP_TLS_CERT=/etc/letsencrypt/live/YOUR_HOST/fullchain.pem
#PALE_SIP_TLS_KEY=/etc/letsencrypt/live/YOUR_HOST/privkey.pem
#PALE_SIP_EXTERNAL_ADDR=YOUR_HOST:5060
#PALE_SIP_TLS_EXTERNAL_ADDR=YOUR_HOST:5061
#PALE_TURN_SERVER=turn:YOUR_HOST:3478
#PALE_DATABASE_URL=host=127.0.0.1 user=pale password=... dbname=pale
#PALE_RETENTION_ENFORCEMENT_INTERVAL_SECS=86400
RUST_LOG=info
EOF
  chown root:root "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
}

ensure_systemd_unit() {
  local bin_path="$1"
  if ! systemctl list-unit-files "$SERVICE_NAME.service" >/dev/null 2>&1; then
    cat >"/etc/systemd/system/$SERVICE_NAME.service" <<EOF
[Unit]
Description=Pale Server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
ExecStart=$bin_path
Restart=on-failure
RestartSec=5s
User=root

[Install]
WantedBy=multi-user.target
EOF
  fi

  install -d -m 0755 "/etc/systemd/system/$SERVICE_NAME.service.d"
  cat >"/etc/systemd/system/$SERVICE_NAME.service.d/override.conf" <<EOF
[Service]
EnvironmentFile=$ENV_FILE
EOF
}

health_check() {
  local http_addr="$1"
  local port
  port="${http_addr##*:}"
  if curl -fsS "http://127.0.0.1:$port/health" >/dev/null; then
    echo "Pale Server is running: http://127.0.0.1:$port/health"
  else
    echo "Pale Server service started, but health check did not answer yet."
    echo "Check logs with: journalctl -u $SERVICE_NAME -e"
  fi
}

main() {
  need_root

  echo "Pale Server installer"
  echo "This installs the package, writes local secrets, and enables systemd."
  echo

  local package_manager http_addr admin_user admin_password sip_backend bin_path
  package_manager="$(detect_os)"
  http_addr="$(prompt_default "HTTP bind address" "127.0.0.1:8080")"
  admin_user="$(prompt_default "Admin username" "admin")"
  admin_password="$(prompt_secret)"
  sip_backend="$(prompt_default "SIP backend (udp-parser = built-in REGISTER/PBX; pjsip disables SIP on no-native builds)" "udp-parser")"
  case "$sip_backend" in
    pjsip|udp-parser) ;;
    *) die "SIP backend must be pjsip or udp-parser" ;;
  esac

  case "$package_manager" in
    apt) install_from_apt ;;
    dnf) install_from_dnf ;;
  esac

  bin_path="$(server_binary)"
  write_env "$http_addr" "$admin_user" "$admin_password" "$sip_backend"
  ensure_systemd_unit "$bin_path"

  systemctl daemon-reload
  systemctl enable --now "$SERVICE_NAME"
  health_check "$http_addr"

  echo
  echo "Config: $ENV_FILE"
  echo "Data:   $DATA_DIR"
  echo "Logs:   journalctl -u $SERVICE_NAME -f"
  echo
  echo "Next for production:"
  echo "  - Put TLS reverse proxy in front of $http_addr"
  echo "  - Set PALE_SIP_TLS_CERT/KEY and PALE_SIP_EXTERNAL_ADDR in $ENV_FILE"
  echo "  - Configure Postgres + coturn (see docs/deploy/linux.md)"
  echo "  - Treat PALE_SERVER_TOKEN as break-glass only"
}

main "$@"
